// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oepgypajfjoyshgannpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcGd5cGFqZmpveXNoZ2FubnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzY1MjksImV4cCI6MjA3NDY1MjUyOX0.QCGiAHOegEP8D-ExtTA43eN9DN_5g_NqAhGVaylgkWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});